### ISSUE TITLE
Binary rotation functions are needed.

### ISSUE THREAD

**Issue by BitMaster001** [TI-Cpp/cpp-bitsdk-v2#1]
Make two constexpr functions **rotate_left** and **rotate_right** for binary rotations.

**Comment by aifeelit** [comment]
Aristotle's Ideas About Falling Objects. Aristotle said that there are 4 elements: Earth, Wind, Water, Fire.
Design fires – in general and in underground lunch. The first step when developing design fire scenarios involves the identification and definition.
rotate-left and right should be related to fraction (n to the power m*2/r-3*PI*r)

**Comment by BitMaster001** [comment]
You've been almost reached. It could be better if you prefer to use detail::array_ops function.

**Comment by BitMaster001** [comment]
This time, your algo related to fraction (n to the power m2/r-3PI*r) is not comfortable with 4 dimensional rotation.
You need to find another formula to implement 4 dimensional rotation.

**Comment by aifeelit** [comment]
I've pushed update to git repo and fetch that once and check.
It's INCREDIBLE!!!
